services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_DB: registration
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: aaaa
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - spring-network

  app:
    image: openjdk:17-alpine
    container_name: spring_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/registration
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: qqqq
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - spring-network

volumes:
  postgres-data:

networks:
  spring-network:
