spring:
    application:
        name: candidature

    datasource:
        url: jdbc:postgresql://localhost:5432/candidature
        username: postgres
        password: qqqq
    
    jpa:
        hibernate: 
            ddl-auto: create-drop

        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: postgresql

server:
    port: 8090



