spring:
    application:
        name: candidature

    datasource:
        url: jdbc:postgresql://localhost:5432/registration
        username: postgres
        password: qqqq
    
    jpa:
        hibernate: 
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: postgresql

    servlet:
        multipart:
            max-file-size: 6MB
            max-request-size: 6MB

    mail:
        host: smtp.gmail.com
        port: 587
        username: mpsolver01@gmail.com
        password: zisb ljyv ywnr rxov
        properties:
            mail.smtp.auth: true
            mail.smtp.starttls.enable: true

server:
    port: 8080
