spring:
    application:
        name: microserviceUser

    datasource:
        url: jdbc:postgresql://localhost:5432/registration
        username: postgres
        password: qqqq
    
    jpa:
        hibernate: 
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: postgresql
    
    servlet:
        multipart:
            max-file-size: 6MB
            max-request-size: 6MB
  
server:
    port: 8090
