eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        prefer-ip-address: true 
        hostname: localhost       
        non-secure-port-enabled: true
        instance-id: ${spring.application.name}:${server.port}

spring:
    application:
        name: MicroserviceUsers

    datasource:
        url: jdbc:postgresql://localhost:5432/registration
        username: postgres
        password: aaaa
    
    jpa:
        hibernate: 
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: postgresql
    
    servlet:
        multipart:
            max-file-size: 6MB
            max-request-size: 6MB
  
server:
    port: 8090
